using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[Serializable]
public class PlayerContext
{
    public Vector3 move;
    public float moveSpeed;
    public float ySpeed;
    public Vector3 rootMotionDelta;
    public Vector3 worldMoveDir;
    public Vector3 airVelocity;
    public Vector3 landingCarryVelocity;
    public Vector2 look;
    public bool grounded;
    public float walkSpeed = 10f;
    public float runSpeed = 20f;
    public float accel = 40f;
    public float jumpSpeed = 6f;
    public float fallSpeed = -15f;
    public float groundedStickForce = -2f;
    public float idleJumpHorizontalSpeed = 0f;
    public float walkJumpHorizontalSpeed = 4f;
    public float runJumpHorizontalSpeed = 8f;
    public float airControlSpeed = 3f;
    public float airControlAcceleration = 10f;
    public int extraJumpCount;
    public int remainingAirJumps;
    public bool flyUnlocked;
    public bool isFlying;
    public bool isGliding;
    public bool jumpHeld;
    public float flyRiseSpeed = 4f;
    public float flyFallSpeed = -2f;
    public float flyHorizontalSpeed = 7f;
    public float flyAcceleration = 14f;
    public float maxFlightEnergy = 3f;
    public float currentFlightEnergy = 3f;
    public float flightEnergyConsumeRate = 1f;
    public float flightEnergyRecoverRate = 3f;
    public bool restoreFlightEnergyImmediatelyOnGround = true;
    public float glideFallSpeed = -2.5f;
    public float glideHorizontalSpeed = 6f;
    public float glideAcceleration = 12f;
    public float hardLandingFallSpeed = 10f;
    public float locomotionBlendDuration = 0.18f;
    public float airborneBlendDuration = 0.12f;
    public float attackBlendDuration = 0.08f;
    public float hitReactionBlendDuration = 0.06f;
    public float landingBlendDuration = 0.1f;
    public float landingCompleteNormalizedTime = 0.98f;
    public float landingCarryDeceleration = 18f;
    public bool jumpPressed;
    public Animator anim;
    public CharacterController cc;
    public int priority = 8;

    public bool isMoving = false;
    public bool isWalkingState;
    public bool isRunningState;
    public bool isLeftPressed;
    public bool isRightPressed;
    public bool attackLayerActive;
    public bool useLegacyAttackLayer = true;
    public bool weaponAttackEnabled = true;
    public bool weaponAttackPlaying;
    public float currentAnimatorSpeed = 1f;

    public string idleAnimStateName = "Idle";
    public string walkAnimStateName = "Walk";
    public string runAnimStateName = "Run";
    public string jumpAnimStateName = "Jump";
    public string fallAnimStateName = "Fall";
    public string flyAnimStateName = "Fly";
    public string wingCloseAnimStateName = "Close";
    public string wingOpenAnimStateName = "Open";
    public string wingFlyAnimStateName = "Fly";
    public string landAnimStateName = "Land";
    public string attackAnimStateName = "ATKTree";
    public string hitAnimStateName = "Hit";
}
